### ISSUE TITLE
Created on is updated whenever the page is reloaded

### ISSUE THREAD

**Issue by algomaster99** [IMGIITRoorkee/omniport-service-developer#2]
![dev-bug](https://user-images.githubusercontent.com/35191225/88489100-e10a5a80-cfaf-11ea-9fe5-eab1d20f95ec.PNG)

### Reproduce

1. Create an app on `Developer` service.
2. Refresh its detail view and you will see how "Created on" updates with each reload.

**Comment by ruddi10** [comment]
Assign it to me

**Comment by algomaster99** [comment]
@ruddi10 it's all yours! Please proceed.

**Comment by ruddi10** [comment]
@algomaster99 made 2 pull requests kindly check
